In [1]:
# Model Evaluation 

In [2]:
# Evaluation for Classification

In [4]:
%matplotlib notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits

In [2]:
dataset = load_digits()

In [5]:
X, y = dataset.data, dataset.target 

In [9]:
len(X)

1797

In [16]:
for class_name, class_count in zip(dataset.target_names,np.bincount(dataset.target)):
    print(class_name,class_count)

0 178
1 182
2 177
3 183
4 181
5 182
6 181
7 179
8 174
9 180


In [13]:
np.bincount(dataset.target)

array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180])

In [14]:
dataset.target

array([0, 1, 2, ..., 8, 9, 8])

In [15]:
dataset.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
y_binary_imbalanced = y.copy()
y_binary_imbalanced[y_binary_imbalanced!=1] = 0

print('original labels:',y[1:30])
print('New binary labels:', y_binary_imbalanced[1:30])

original labels: [1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]
New binary labels: [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]


In [19]:
np.bincount(y_binary_imbalanced)

array([1615,  182])

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y_binary_imbalanced,random_state=0)
from sklearn.svm import SVC
svm = SVC(kernel='rbf',C=1).fit(X_train, y_train)
svm.score(X_test,y_test)

0.9088888888888889

In [22]:
from sklearn.dummy import DummyClassifier
dummy_majority = DummyClassifier(strategy = 'most_frequent').fit(X_train,y_train)
y_dummy_predictions = dummy_majority.predict(X_test)
y_dummy_predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [23]:
dummy_majority.score(X_test, y_test)

0.9044444444444445

In [11]:
# evaluation for classification
# accuracy and confusion metrix

import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

dataset = load_digits()
X, y = dataset.data, dataset.target

for class_name, class_count in zip(dataset.target_names, np.bincount(dataset.target)):
    print(class_name, class_count)
    
# creating a dataset with imbalanced binary class:

y_binary_imbalanced = y.copy()
y_binary_imbalanced[y_binary_imbalanced != 1 ] = 0

print('Original labels:\t', y[1:30])
print('New binary labels:\t', y_binary_imbalanced[1:30])

# Negative class (0) is the most frequent class
np.bincount(y_binary_imbalanced)

X_train, X_test, y_train, y_test = train_test_split(X, y_binary_imbalanced, random_state = 0)

# Accuracy of Support Vector Machine Classifier
from sklearn.svm import SVC
svm = SVC(kernel = 'rbf', C=1).fit(X_train, y_train)
svm.score(X_test, y_test)

svm = SVC(kernel ='linear',C=1).fit(X_train, y_train)
svm.score(X_test, y_test)

# Dummy Classifier

from sklearn.dummy import DummyClassifier

dummy_majority = DummyClassifier(strategy = 'most_frequent').fit(X_train, y_train)
y_dummy_predictions = dummy_majority.predict(X_test)
y_dummy_predicitons
dummy_majority.score(X_test,y_test)



0 178
1 182
2 177
3 183
4 181
5 182
6 181
7 179
8 174
9 180
Original labels:	 [1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]
New binary labels:	 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]


0.9044444444444445

In [ ]:
from sklearn.metrics import precision_recall_curve

prec