In [1]:
#Cross- Validation

In [5]:
# CrossValidation

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, cross_val_score
import pandas as pd
import numpy as np

fruits = pd.read_table('fruit_data_with_colors.txt')
X_fruits = fruits[['height','width']]
y_fruits = fruits['fruit_label']

clf = KNeighborsClassifier(n_neighbors = 5)
X = X_fruits.values
y = y_fruits.values

cv_scores = cross_val_score(clf, X, y)

print('Cross-validation scores (3-fold):',cv_scores)
print('Mean cross-validation score (3-fold): {:.3f}'
      .format(np.mean(cv_scores)))

Cross-validation scores (3-fold): [0.77272727 0.73684211 0.83333333]
Mean cross-validation score (3-fold): 0.781


In [7]:
#validation curve example
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import validation_curve
import pandas as pd
import numpy as np

fruits = pd.read_table('fruit_data_with_colors.txt')
X_fruits = fruits[['height','width']]
y_fruits = fruits['fruit_label']

clf = KNeighborsClassifier(n_neighbors = 5)
X = X_fruits.values
y = y_fruits.values

param_range = np.logspace(-3,3,4)
train_scores, test_scores = validation_curve(SVC(),X, y,param_name= 'gamma',
                                             param_range=param_range,cv=3)

In [8]:
print(train_scores)

[[0.48648649 0.425      0.41463415]
 [0.83783784 0.725      0.75609756]
 [0.91891892 0.9        0.92682927]
 [1.         1.         0.97560976]]


In [9]:
print(test_scores)

[[0.45454545 0.31578947 0.33333333]
 [0.81818182 0.68421053 0.61111111]
 [0.40909091 0.84210526 0.66666667]
 [0.36363636 0.21052632 0.38888889]]
